{% set name = "scikit-spatial" %}
{% set version = "8.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: a51609797794fdb0ce33a946a65e2653d5f1276e60265957a6a83b8cd33432cd

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }},<3.12
    - matplotlib-base >=3,<4
    - numpy >=1.20,<2
    - scipy >=1.9,<2

test:
  requires:
    - python {{ python_min }}
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
