{% set name = "scikit-spatial" %}
{% set version = "7.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 988a791d3e9cfdd80a4681ee9728c096a5864fb2c6986ee9c9eb50fcd467c659

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8,<3.12
    - pip
    - poetry >1,<2
  run:
    - python >=3.8,<3.12
    - matplotlib-base >=3,<4
    - numpy >=1.20,<2
    - scipy >=1.9,<2

test:
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
