{% set name = "scikit-spatial" %}
{% set version = "8.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 8ca06d4350b45f9c7de039944c1749cc9e0fadbf81048f59204676a0c4c6830d

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry >1,<2
  run:
    - python >={{ python_min }},<3.12
    - matplotlib-base >=3,<4
    - numpy >=1.20,<2
    - scipy >=1.9,<2

test:
  requires:
    - python {{ python_min }}
  imports:
    - skspatial
    - skspatial.objects

about:
  home: https://github.com/ajhynes7/scikit-spatial
  doc_url: https://scikit-spatial.readthedocs.io
  summary: Spatial objects and computations based on NumPy arrays.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ajhynes7
